#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ASPNETDB")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertaspnet_User(aspnet_User instance);
  partial void Updateaspnet_User(aspnet_User instance);
  partial void Deleteaspnet_User(aspnet_User instance);
  partial void Insertmessage(message instance);
  partial void Updatemessage(message instance);
  partial void Deletemessage(message instance);
  partial void InsertViewed(Viewed instance);
  partial void UpdateViewed(Viewed instance);
  partial void DeleteViewed(Viewed instance);
  partial void InsertWyglad(Wyglad instance);
  partial void UpdateWyglad(Wyglad instance);
  partial void DeleteWyglad(Wyglad instance);
  partial void InsertSport(Sport instance);
  partial void UpdateSport(Sport instance);
  partial void DeleteSport(Sport instance);
  partial void Insertmessage_sent(message_sent instance);
  partial void Updatemessage_sent(message_sent instance);
  partial void Deletemessage_sent(message_sent instance);
  partial void Insertmessage1(message1 instance);
  partial void Updatemessage1(message1 instance);
  partial void Deletemessage1(message1 instance);
  partial void Insertplec(plec instance);
  partial void Updateplec(plec instance);
  partial void Deleteplec(plec instance);
  partial void Insertuser_profile(user_profile instance);
  partial void Updateuser_profile(user_profile instance);
  partial void Deleteuser_profile(user_profile instance);
  partial void Insertuser_sport(user_sport instance);
  partial void Updateuser_sport(user_sport instance);
  partial void Deleteuser_sport(user_sport instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FriendsConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<friend> friends
	{
		get
		{
			return this.GetTable<friend>();
		}
	}
	
	public System.Data.Linq.Table<aspnet_User> aspnet_Users
	{
		get
		{
			return this.GetTable<aspnet_User>();
		}
	}
	
	public System.Data.Linq.Table<message> messages
	{
		get
		{
			return this.GetTable<message>();
		}
	}
	
	public System.Data.Linq.Table<Viewed> Vieweds
	{
		get
		{
			return this.GetTable<Viewed>();
		}
	}
	
	public System.Data.Linq.Table<Wyglad> Wyglads
	{
		get
		{
			return this.GetTable<Wyglad>();
		}
	}
	
	public System.Data.Linq.Table<Sport> Sports
	{
		get
		{
			return this.GetTable<Sport>();
		}
	}
	
	public System.Data.Linq.Table<message_sent> message_sents
	{
		get
		{
			return this.GetTable<message_sent>();
		}
	}
	
	public System.Data.Linq.Table<message1> message1s
	{
		get
		{
			return this.GetTable<message1>();
		}
	}
	
	public System.Data.Linq.Table<plec> plecs
	{
		get
		{
			return this.GetTable<plec>();
		}
	}
	
	public System.Data.Linq.Table<user_profile> user_profiles
	{
		get
		{
			return this.GetTable<user_profile>();
		}
	}
	
	public System.Data.Linq.Table<user_sport> user_sports
	{
		get
		{
			return this.GetTable<user_sport>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PokazOdwiedzone")]
	public ISingleResult<PokazOdwiedzoneResult> PokazOdwiedzone([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string userid)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid);
		return ((ISingleResult<PokazOdwiedzoneResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Szukaj")]
	public ISingleResult<SzukajResult> Szukaj([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> gender, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dateUp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dateDown, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string wojewodztwo_id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gender, dateUp, dateDown, userid, wojewodztwo_id);
		return ((ISingleResult<SzukajResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CountWiek", IsComposable=true)]
	public IQueryable<CountWiekResult> CountWiek([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(11)")] string dataurodzin)
	{
		return this.CreateMethodCallQuery<CountWiekResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dataurodzin);
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.friends")]
public partial class friend
{
	
	private System.Guid _userid;
	
	private System.Guid _friendid;
	
	public friend()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this._userid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_friendid", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid friendid
	{
		get
		{
			return this._friendid;
		}
		set
		{
			if ((this._friendid != value))
			{
				this._friendid = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.aspnet_Users")]
public partial class aspnet_User : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _ApplicationId;
	
	private System.Guid _UserId;
	
	private string _UserName;
	
	private string _LoweredUserName;
	
	private string _MobileAlias;
	
	private bool _IsAnonymous;
	
	private System.DateTime _LastActivityDate;
	
	private EntitySet<message> _messages;
	
	private EntitySet<message> _messages1;
	
	private EntityRef<Wyglad> _Wyglad;
	
	private EntitySet<message_sent> _message_sents;
	
	private EntitySet<message_sent> _message_sents1;
	
	private EntitySet<message1> _message1s;
	
	private EntitySet<message1> _message1s1;
	
	private EntityRef<user_profile> _user_profile;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApplicationIdChanging(System.Guid value);
    partial void OnApplicationIdChanged();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnLoweredUserNameChanging(string value);
    partial void OnLoweredUserNameChanged();
    partial void OnMobileAliasChanging(string value);
    partial void OnMobileAliasChanged();
    partial void OnIsAnonymousChanging(bool value);
    partial void OnIsAnonymousChanged();
    partial void OnLastActivityDateChanging(System.DateTime value);
    partial void OnLastActivityDateChanged();
    #endregion
	
	public aspnet_User()
	{
		this._messages = new EntitySet<message>(new Action<message>(this.attach_messages), new Action<message>(this.detach_messages));
		this._messages1 = new EntitySet<message>(new Action<message>(this.attach_messages1), new Action<message>(this.detach_messages1));
		this._Wyglad = default(EntityRef<Wyglad>);
		this._message_sents = new EntitySet<message_sent>(new Action<message_sent>(this.attach_message_sents), new Action<message_sent>(this.detach_message_sents));
		this._message_sents1 = new EntitySet<message_sent>(new Action<message_sent>(this.attach_message_sents1), new Action<message_sent>(this.detach_message_sents1));
		this._message1s = new EntitySet<message1>(new Action<message1>(this.attach_message1s), new Action<message1>(this.detach_message1s));
		this._message1s1 = new EntitySet<message1>(new Action<message1>(this.attach_message1s1), new Action<message1>(this.detach_message1s1));
		this._user_profile = default(EntityRef<user_profile>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationId", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid ApplicationId
	{
		get
		{
			return this._ApplicationId;
		}
		set
		{
			if ((this._ApplicationId != value))
			{
				this.OnApplicationIdChanging(value);
				this.SendPropertyChanging();
				this._ApplicationId = value;
				this.SendPropertyChanged("ApplicationId");
				this.OnApplicationIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				this.OnUserIdChanging(value);
				this.SendPropertyChanging();
				this._UserId = value;
				this.SendPropertyChanged("UserId");
				this.OnUserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this.OnUserNameChanging(value);
				this.SendPropertyChanging();
				this._UserName = value;
				this.SendPropertyChanged("UserName");
				this.OnUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoweredUserName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
	public string LoweredUserName
	{
		get
		{
			return this._LoweredUserName;
		}
		set
		{
			if ((this._LoweredUserName != value))
			{
				this.OnLoweredUserNameChanging(value);
				this.SendPropertyChanging();
				this._LoweredUserName = value;
				this.SendPropertyChanged("LoweredUserName");
				this.OnLoweredUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileAlias", DbType="NVarChar(16)")]
	public string MobileAlias
	{
		get
		{
			return this._MobileAlias;
		}
		set
		{
			if ((this._MobileAlias != value))
			{
				this.OnMobileAliasChanging(value);
				this.SendPropertyChanging();
				this._MobileAlias = value;
				this.SendPropertyChanged("MobileAlias");
				this.OnMobileAliasChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAnonymous", DbType="Bit NOT NULL")]
	public bool IsAnonymous
	{
		get
		{
			return this._IsAnonymous;
		}
		set
		{
			if ((this._IsAnonymous != value))
			{
				this.OnIsAnonymousChanging(value);
				this.SendPropertyChanging();
				this._IsAnonymous = value;
				this.SendPropertyChanged("IsAnonymous");
				this.OnIsAnonymousChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActivityDate", DbType="DateTime NOT NULL")]
	public System.DateTime LastActivityDate
	{
		get
		{
			return this._LastActivityDate;
		}
		set
		{
			if ((this._LastActivityDate != value))
			{
				this.OnLastActivityDateChanging(value);
				this.SendPropertyChanging();
				this._LastActivityDate = value;
				this.SendPropertyChanged("LastActivityDate");
				this.OnLastActivityDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_message", Storage="_messages", ThisKey="UserId", OtherKey="receivid")]
	public EntitySet<message> messages
	{
		get
		{
			return this._messages;
		}
		set
		{
			this._messages.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_message1", Storage="_messages1", ThisKey="UserId", OtherKey="receivid")]
	public EntitySet<message> messages1
	{
		get
		{
			return this._messages1;
		}
		set
		{
			this._messages1.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_Wyglad", Storage="_Wyglad", ThisKey="UserId", OtherKey="userid", IsUnique=true, IsForeignKey=false)]
	public Wyglad Wyglad
	{
		get
		{
			return this._Wyglad.Entity;
		}
		set
		{
			Wyglad previousValue = this._Wyglad.Entity;
			if (((previousValue != value) 
						|| (this._Wyglad.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Wyglad.Entity = null;
					previousValue.aspnet_User = null;
				}
				this._Wyglad.Entity = value;
				if ((value != null))
				{
					value.aspnet_User = this;
				}
				this.SendPropertyChanged("Wyglad");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_message_sent", Storage="_message_sents", ThisKey="UserId", OtherKey="receiver_id")]
	public EntitySet<message_sent> message_sents
	{
		get
		{
			return this._message_sents;
		}
		set
		{
			this._message_sents.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_message_sent1", Storage="_message_sents1", ThisKey="UserId", OtherKey="receiver_id")]
	public EntitySet<message_sent> message_sents1
	{
		get
		{
			return this._message_sents1;
		}
		set
		{
			this._message_sents1.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_message11", Storage="_message1s", ThisKey="UserId", OtherKey="receivid")]
	public EntitySet<message1> message1s
	{
		get
		{
			return this._message1s;
		}
		set
		{
			this._message1s.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_message12", Storage="_message1s1", ThisKey="UserId", OtherKey="receivid")]
	public EntitySet<message1> message1s1
	{
		get
		{
			return this._message1s1;
		}
		set
		{
			this._message1s1.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_user_profile", Storage="_user_profile", ThisKey="UserId", OtherKey="userid", IsUnique=true, IsForeignKey=false)]
	public user_profile user_profile
	{
		get
		{
			return this._user_profile.Entity;
		}
		set
		{
			user_profile previousValue = this._user_profile.Entity;
			if (((previousValue != value) 
						|| (this._user_profile.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._user_profile.Entity = null;
					previousValue.aspnet_User = null;
				}
				this._user_profile.Entity = value;
				if ((value != null))
				{
					value.aspnet_User = this;
				}
				this.SendPropertyChanged("user_profile");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_messages(message entity)
	{
		this.SendPropertyChanging();
		entity.aspnet_User = this;
	}
	
	private void detach_messages(message entity)
	{
		this.SendPropertyChanging();
		entity.aspnet_User = null;
	}
	
	private void attach_messages1(message entity)
	{
		this.SendPropertyChanging();
		entity.aspnet_User1 = this;
	}
	
	private void detach_messages1(message entity)
	{
		this.SendPropertyChanging();
		entity.aspnet_User1 = null;
	}
	
	private void attach_message_sents(message_sent entity)
	{
		this.SendPropertyChanging();
		entity.aspnet_User = this;
	}
	
	private void detach_message_sents(message_sent entity)
	{
		this.SendPropertyChanging();
		entity.aspnet_User = null;
	}
	
	private void attach_message_sents1(message_sent entity)
	{
		this.SendPropertyChanging();
		entity.aspnet_User1 = this;
	}
	
	private void detach_message_sents1(message_sent entity)
	{
		this.SendPropertyChanging();
		entity.aspnet_User1 = null;
	}
	
	private void attach_message1s(message1 entity)
	{
		this.SendPropertyChanging();
		entity.aspnet_User = this;
	}
	
	private void detach_message1s(message1 entity)
	{
		this.SendPropertyChanging();
		entity.aspnet_User = null;
	}
	
	private void attach_message1s1(message1 entity)
	{
		this.SendPropertyChanging();
		entity.aspnet_User1 = this;
	}
	
	private void detach_message1s1(message1 entity)
	{
		this.SendPropertyChanging();
		entity.aspnet_User1 = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.message")]
public partial class message : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _msgid;
	
	private System.Nullable<System.Guid> _sendid;
	
	private System.Nullable<System.Guid> _receivid;
	
	private string _mssg;
	
	private System.Nullable<System.DateTime> _sentdate;
	
	private EntityRef<aspnet_User> _aspnet_User;
	
	private EntityRef<aspnet_User> _aspnet_User1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmsgidChanging(int value);
    partial void OnmsgidChanged();
    partial void OnsendidChanging(System.Nullable<System.Guid> value);
    partial void OnsendidChanged();
    partial void OnreceividChanging(System.Nullable<System.Guid> value);
    partial void OnreceividChanged();
    partial void OnmssgChanging(string value);
    partial void OnmssgChanged();
    partial void OnsentdateChanging(System.Nullable<System.DateTime> value);
    partial void OnsentdateChanged();
    #endregion
	
	public message()
	{
		this._aspnet_User = default(EntityRef<aspnet_User>);
		this._aspnet_User1 = default(EntityRef<aspnet_User>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msgid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int msgid
	{
		get
		{
			return this._msgid;
		}
		set
		{
			if ((this._msgid != value))
			{
				this.OnmsgidChanging(value);
				this.SendPropertyChanging();
				this._msgid = value;
				this.SendPropertyChanged("msgid");
				this.OnmsgidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sendid", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> sendid
	{
		get
		{
			return this._sendid;
		}
		set
		{
			if ((this._sendid != value))
			{
				this.OnsendidChanging(value);
				this.SendPropertyChanging();
				this._sendid = value;
				this.SendPropertyChanged("sendid");
				this.OnsendidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receivid", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> receivid
	{
		get
		{
			return this._receivid;
		}
		set
		{
			if ((this._receivid != value))
			{
				if ((this._aspnet_User.HasLoadedOrAssignedValue || this._aspnet_User1.HasLoadedOrAssignedValue))
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnreceividChanging(value);
				this.SendPropertyChanging();
				this._receivid = value;
				this.SendPropertyChanged("receivid");
				this.OnreceividChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mssg", DbType="NVarChar(MAX)")]
	public string mssg
	{
		get
		{
			return this._mssg;
		}
		set
		{
			if ((this._mssg != value))
			{
				this.OnmssgChanging(value);
				this.SendPropertyChanging();
				this._mssg = value;
				this.SendPropertyChanged("mssg");
				this.OnmssgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sentdate", DbType="DateTime")]
	public System.Nullable<System.DateTime> sentdate
	{
		get
		{
			return this._sentdate;
		}
		set
		{
			if ((this._sentdate != value))
			{
				this.OnsentdateChanging(value);
				this.SendPropertyChanging();
				this._sentdate = value;
				this.SendPropertyChanged("sentdate");
				this.OnsentdateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_message", Storage="_aspnet_User", ThisKey="receivid", OtherKey="UserId", IsForeignKey=true)]
	public aspnet_User aspnet_User
	{
		get
		{
			return this._aspnet_User.Entity;
		}
		set
		{
			aspnet_User previousValue = this._aspnet_User.Entity;
			if (((previousValue != value) 
						|| (this._aspnet_User.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._aspnet_User.Entity = null;
					previousValue.messages.Remove(this);
				}
				this._aspnet_User.Entity = value;
				if ((value != null))
				{
					value.messages.Add(this);
					this._receivid = value.UserId;
				}
				else
				{
					this._receivid = default(Nullable<System.Guid>);
				}
				this.SendPropertyChanged("aspnet_User");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_message1", Storage="_aspnet_User1", ThisKey="receivid", OtherKey="UserId", IsForeignKey=true)]
	public aspnet_User aspnet_User1
	{
		get
		{
			return this._aspnet_User1.Entity;
		}
		set
		{
			aspnet_User previousValue = this._aspnet_User1.Entity;
			if (((previousValue != value) 
						|| (this._aspnet_User1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._aspnet_User1.Entity = null;
					previousValue.messages1.Remove(this);
				}
				this._aspnet_User1.Entity = value;
				if ((value != null))
				{
					value.messages1.Add(this);
					this._receivid = value.UserId;
				}
				else
				{
					this._receivid = default(Nullable<System.Guid>);
				}
				this.SendPropertyChanged("aspnet_User1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Viewed")]
public partial class Viewed : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _OdwiedzanyId;
	
	private System.Guid _OdwiedzilId;
	
	private System.DateTime _Data;
	
	private int _viewed1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOdwiedzanyIdChanging(System.Guid value);
    partial void OnOdwiedzanyIdChanged();
    partial void OnOdwiedzilIdChanging(System.Guid value);
    partial void OnOdwiedzilIdChanged();
    partial void OnDataChanging(System.DateTime value);
    partial void OnDataChanged();
    partial void Onviewed1Changing(int value);
    partial void Onviewed1Changed();
    #endregion
	
	public Viewed()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdwiedzanyId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid OdwiedzanyId
	{
		get
		{
			return this._OdwiedzanyId;
		}
		set
		{
			if ((this._OdwiedzanyId != value))
			{
				this.OnOdwiedzanyIdChanging(value);
				this.SendPropertyChanging();
				this._OdwiedzanyId = value;
				this.SendPropertyChanged("OdwiedzanyId");
				this.OnOdwiedzanyIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdwiedzilId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid OdwiedzilId
	{
		get
		{
			return this._OdwiedzilId;
		}
		set
		{
			if ((this._OdwiedzilId != value))
			{
				this.OnOdwiedzilIdChanging(value);
				this.SendPropertyChanging();
				this._OdwiedzilId = value;
				this.SendPropertyChanged("OdwiedzilId");
				this.OnOdwiedzilIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
	public System.DateTime Data
	{
		get
		{
			return this._Data;
		}
		set
		{
			if ((this._Data != value))
			{
				this.OnDataChanging(value);
				this.SendPropertyChanging();
				this._Data = value;
				this.SendPropertyChanged("Data");
				this.OnDataChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="viewed", Storage="_viewed1", DbType="Int NOT NULL")]
	public int viewed1
	{
		get
		{
			return this._viewed1;
		}
		set
		{
			if ((this._viewed1 != value))
			{
				this.Onviewed1Changing(value);
				this.SendPropertyChanging();
				this._viewed1 = value;
				this.SendPropertyChanged("viewed1");
				this.Onviewed1Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Wyglad")]
public partial class Wyglad : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _userid;
	
	private System.Nullable<int> _wzrost;
	
	private System.Nullable<int> _waga;
	
	private System.Nullable<int> _budowa_ciala_id;
	
	private EntityRef<aspnet_User> _aspnet_User;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuseridChanging(System.Guid value);
    partial void OnuseridChanged();
    partial void OnwzrostChanging(System.Nullable<int> value);
    partial void OnwzrostChanged();
    partial void OnwagaChanging(System.Nullable<int> value);
    partial void OnwagaChanged();
    partial void Onbudowa_ciala_idChanging(System.Nullable<int> value);
    partial void Onbudowa_ciala_idChanged();
    #endregion
	
	public Wyglad()
	{
		this._aspnet_User = default(EntityRef<aspnet_User>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				if (this._aspnet_User.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnuseridChanging(value);
				this.SendPropertyChanging();
				this._userid = value;
				this.SendPropertyChanged("userid");
				this.OnuseridChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wzrost", DbType="Int")]
	public System.Nullable<int> wzrost
	{
		get
		{
			return this._wzrost;
		}
		set
		{
			if ((this._wzrost != value))
			{
				this.OnwzrostChanging(value);
				this.SendPropertyChanging();
				this._wzrost = value;
				this.SendPropertyChanged("wzrost");
				this.OnwzrostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_waga", DbType="Int")]
	public System.Nullable<int> waga
	{
		get
		{
			return this._waga;
		}
		set
		{
			if ((this._waga != value))
			{
				this.OnwagaChanging(value);
				this.SendPropertyChanging();
				this._waga = value;
				this.SendPropertyChanged("waga");
				this.OnwagaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_budowa_ciala_id", DbType="Int")]
	public System.Nullable<int> budowa_ciala_id
	{
		get
		{
			return this._budowa_ciala_id;
		}
		set
		{
			if ((this._budowa_ciala_id != value))
			{
				this.Onbudowa_ciala_idChanging(value);
				this.SendPropertyChanging();
				this._budowa_ciala_id = value;
				this.SendPropertyChanged("budowa_ciala_id");
				this.Onbudowa_ciala_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_Wyglad", Storage="_aspnet_User", ThisKey="userid", OtherKey="UserId", IsForeignKey=true)]
	public aspnet_User aspnet_User
	{
		get
		{
			return this._aspnet_User.Entity;
		}
		set
		{
			aspnet_User previousValue = this._aspnet_User.Entity;
			if (((previousValue != value) 
						|| (this._aspnet_User.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._aspnet_User.Entity = null;
					previousValue.Wyglad = null;
				}
				this._aspnet_User.Entity = value;
				if ((value != null))
				{
					value.Wyglad = this;
					this._userid = value.UserId;
				}
				else
				{
					this._userid = default(System.Guid);
				}
				this.SendPropertyChanged("aspnet_User");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sport")]
public partial class Sport : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _sport_id;
	
	private string _sport_opis;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsport_idChanging(int value);
    partial void Onsport_idChanged();
    partial void Onsport_opisChanging(string value);
    partial void Onsport_opisChanged();
    #endregion
	
	public Sport()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sport_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int sport_id
	{
		get
		{
			return this._sport_id;
		}
		set
		{
			if ((this._sport_id != value))
			{
				this.Onsport_idChanging(value);
				this.SendPropertyChanging();
				this._sport_id = value;
				this.SendPropertyChanged("sport_id");
				this.Onsport_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sport_opis", DbType="NVarChar(50)")]
	public string sport_opis
	{
		get
		{
			return this._sport_opis;
		}
		set
		{
			if ((this._sport_opis != value))
			{
				this.Onsport_opisChanging(value);
				this.SendPropertyChanging();
				this._sport_opis = value;
				this.SendPropertyChanged("sport_opis");
				this.Onsport_opisChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.message_sent")]
public partial class message_sent : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _msgid;
	
	private System.Nullable<System.Guid> _sender_id;
	
	private System.Nullable<System.Guid> _receiver_id;
	
	private string _mssg;
	
	private System.Nullable<System.DateTime> _sentdate;
	
	private EntityRef<aspnet_User> _aspnet_User;
	
	private EntityRef<aspnet_User> _aspnet_User1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmsgidChanging(int value);
    partial void OnmsgidChanged();
    partial void Onsender_idChanging(System.Nullable<System.Guid> value);
    partial void Onsender_idChanged();
    partial void Onreceiver_idChanging(System.Nullable<System.Guid> value);
    partial void Onreceiver_idChanged();
    partial void OnmssgChanging(string value);
    partial void OnmssgChanged();
    partial void OnsentdateChanging(System.Nullable<System.DateTime> value);
    partial void OnsentdateChanged();
    #endregion
	
	public message_sent()
	{
		this._aspnet_User = default(EntityRef<aspnet_User>);
		this._aspnet_User1 = default(EntityRef<aspnet_User>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msgid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int msgid
	{
		get
		{
			return this._msgid;
		}
		set
		{
			if ((this._msgid != value))
			{
				this.OnmsgidChanging(value);
				this.SendPropertyChanging();
				this._msgid = value;
				this.SendPropertyChanged("msgid");
				this.OnmsgidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sender_id", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> sender_id
	{
		get
		{
			return this._sender_id;
		}
		set
		{
			if ((this._sender_id != value))
			{
				this.Onsender_idChanging(value);
				this.SendPropertyChanging();
				this._sender_id = value;
				this.SendPropertyChanged("sender_id");
				this.Onsender_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receiver_id", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> receiver_id
	{
		get
		{
			return this._receiver_id;
		}
		set
		{
			if ((this._receiver_id != value))
			{
				if ((this._aspnet_User.HasLoadedOrAssignedValue || this._aspnet_User1.HasLoadedOrAssignedValue))
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onreceiver_idChanging(value);
				this.SendPropertyChanging();
				this._receiver_id = value;
				this.SendPropertyChanged("receiver_id");
				this.Onreceiver_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mssg", DbType="NVarChar(MAX)")]
	public string mssg
	{
		get
		{
			return this._mssg;
		}
		set
		{
			if ((this._mssg != value))
			{
				this.OnmssgChanging(value);
				this.SendPropertyChanging();
				this._mssg = value;
				this.SendPropertyChanged("mssg");
				this.OnmssgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sentdate", DbType="DateTime")]
	public System.Nullable<System.DateTime> sentdate
	{
		get
		{
			return this._sentdate;
		}
		set
		{
			if ((this._sentdate != value))
			{
				this.OnsentdateChanging(value);
				this.SendPropertyChanging();
				this._sentdate = value;
				this.SendPropertyChanged("sentdate");
				this.OnsentdateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_message_sent", Storage="_aspnet_User", ThisKey="receiver_id", OtherKey="UserId", IsForeignKey=true)]
	public aspnet_User aspnet_User
	{
		get
		{
			return this._aspnet_User.Entity;
		}
		set
		{
			aspnet_User previousValue = this._aspnet_User.Entity;
			if (((previousValue != value) 
						|| (this._aspnet_User.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._aspnet_User.Entity = null;
					previousValue.message_sents.Remove(this);
				}
				this._aspnet_User.Entity = value;
				if ((value != null))
				{
					value.message_sents.Add(this);
					this._receiver_id = value.UserId;
				}
				else
				{
					this._receiver_id = default(Nullable<System.Guid>);
				}
				this.SendPropertyChanged("aspnet_User");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_message_sent1", Storage="_aspnet_User1", ThisKey="receiver_id", OtherKey="UserId", IsForeignKey=true)]
	public aspnet_User aspnet_User1
	{
		get
		{
			return this._aspnet_User1.Entity;
		}
		set
		{
			aspnet_User previousValue = this._aspnet_User1.Entity;
			if (((previousValue != value) 
						|| (this._aspnet_User1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._aspnet_User1.Entity = null;
					previousValue.message_sents1.Remove(this);
				}
				this._aspnet_User1.Entity = value;
				if ((value != null))
				{
					value.message_sents1.Add(this);
					this._receiver_id = value.UserId;
				}
				else
				{
					this._receiver_id = default(Nullable<System.Guid>);
				}
				this.SendPropertyChanged("aspnet_User1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.message")]
public partial class message1 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _msgid;
	
	private System.Nullable<System.Guid> _sendid;
	
	private System.Nullable<System.Guid> _receivid;
	
	private string _mssg;
	
	private System.Nullable<System.DateTime> _sentdate;
	
	private EntityRef<aspnet_User> _aspnet_User;
	
	private EntityRef<aspnet_User> _aspnet_User1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmsgidChanging(int value);
    partial void OnmsgidChanged();
    partial void OnsendidChanging(System.Nullable<System.Guid> value);
    partial void OnsendidChanged();
    partial void OnreceividChanging(System.Nullable<System.Guid> value);
    partial void OnreceividChanged();
    partial void OnmssgChanging(string value);
    partial void OnmssgChanged();
    partial void OnsentdateChanging(System.Nullable<System.DateTime> value);
    partial void OnsentdateChanged();
    #endregion
	
	public message1()
	{
		this._aspnet_User = default(EntityRef<aspnet_User>);
		this._aspnet_User1 = default(EntityRef<aspnet_User>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msgid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int msgid
	{
		get
		{
			return this._msgid;
		}
		set
		{
			if ((this._msgid != value))
			{
				this.OnmsgidChanging(value);
				this.SendPropertyChanging();
				this._msgid = value;
				this.SendPropertyChanged("msgid");
				this.OnmsgidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sendid", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> sendid
	{
		get
		{
			return this._sendid;
		}
		set
		{
			if ((this._sendid != value))
			{
				this.OnsendidChanging(value);
				this.SendPropertyChanging();
				this._sendid = value;
				this.SendPropertyChanged("sendid");
				this.OnsendidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receivid", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> receivid
	{
		get
		{
			return this._receivid;
		}
		set
		{
			if ((this._receivid != value))
			{
				if ((this._aspnet_User.HasLoadedOrAssignedValue || this._aspnet_User1.HasLoadedOrAssignedValue))
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnreceividChanging(value);
				this.SendPropertyChanging();
				this._receivid = value;
				this.SendPropertyChanged("receivid");
				this.OnreceividChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mssg", DbType="NVarChar(MAX)")]
	public string mssg
	{
		get
		{
			return this._mssg;
		}
		set
		{
			if ((this._mssg != value))
			{
				this.OnmssgChanging(value);
				this.SendPropertyChanging();
				this._mssg = value;
				this.SendPropertyChanged("mssg");
				this.OnmssgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sentdate", DbType="DateTime")]
	public System.Nullable<System.DateTime> sentdate
	{
		get
		{
			return this._sentdate;
		}
		set
		{
			if ((this._sentdate != value))
			{
				this.OnsentdateChanging(value);
				this.SendPropertyChanging();
				this._sentdate = value;
				this.SendPropertyChanged("sentdate");
				this.OnsentdateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_message11", Storage="_aspnet_User", ThisKey="receivid", OtherKey="UserId", IsForeignKey=true)]
	public aspnet_User aspnet_User
	{
		get
		{
			return this._aspnet_User.Entity;
		}
		set
		{
			aspnet_User previousValue = this._aspnet_User.Entity;
			if (((previousValue != value) 
						|| (this._aspnet_User.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._aspnet_User.Entity = null;
					previousValue.message1s.Remove(this);
				}
				this._aspnet_User.Entity = value;
				if ((value != null))
				{
					value.message1s.Add(this);
					this._receivid = value.UserId;
				}
				else
				{
					this._receivid = default(Nullable<System.Guid>);
				}
				this.SendPropertyChanged("aspnet_User");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_message12", Storage="_aspnet_User1", ThisKey="receivid", OtherKey="UserId", IsForeignKey=true)]
	public aspnet_User aspnet_User1
	{
		get
		{
			return this._aspnet_User1.Entity;
		}
		set
		{
			aspnet_User previousValue = this._aspnet_User1.Entity;
			if (((previousValue != value) 
						|| (this._aspnet_User1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._aspnet_User1.Entity = null;
					previousValue.message1s1.Remove(this);
				}
				this._aspnet_User1.Entity = value;
				if ((value != null))
				{
					value.message1s1.Add(this);
					this._receivid = value.UserId;
				}
				else
				{
					this._receivid = default(Nullable<System.Guid>);
				}
				this.SendPropertyChanged("aspnet_User1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.plec")]
public partial class plec : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _plec_Id;
	
	private string _plec1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onplec_IdChanging(int value);
    partial void Onplec_IdChanged();
    partial void Onplec1Changing(string value);
    partial void Onplec1Changed();
    #endregion
	
	public plec()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plec_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int plec_Id
	{
		get
		{
			return this._plec_Id;
		}
		set
		{
			if ((this._plec_Id != value))
			{
				this.Onplec_IdChanging(value);
				this.SendPropertyChanging();
				this._plec_Id = value;
				this.SendPropertyChanged("plec_Id");
				this.Onplec_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="plec", Storage="_plec1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string plec1
	{
		get
		{
			return this._plec1;
		}
		set
		{
			if ((this._plec1 != value))
			{
				this.Onplec1Changing(value);
				this.SendPropertyChanging();
				this._plec1 = value;
				this.SendPropertyChanged("plec1");
				this.Onplec1Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_profile")]
public partial class user_profile : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _userid;
	
	private string _fullname;
	
	private System.Nullable<int> _plec_id;
	
	private System.Nullable<System.DateTime> _birthdate;
	
	private string _opis;
	
	private System.Nullable<int> _wojewodztwo_id;
	
	private EntityRef<aspnet_User> _aspnet_User;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuseridChanging(System.Guid value);
    partial void OnuseridChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void Onplec_idChanging(System.Nullable<int> value);
    partial void Onplec_idChanged();
    partial void OnbirthdateChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdateChanged();
    partial void OnopisChanging(string value);
    partial void OnopisChanged();
    partial void Onwojewodztwo_idChanging(System.Nullable<int> value);
    partial void Onwojewodztwo_idChanged();
    #endregion
	
	public user_profile()
	{
		this._aspnet_User = default(EntityRef<aspnet_User>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				if (this._aspnet_User.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnuseridChanging(value);
				this.SendPropertyChanging();
				this._userid = value;
				this.SendPropertyChanged("userid");
				this.OnuseridChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(50)")]
	public string fullname
	{
		get
		{
			return this._fullname;
		}
		set
		{
			if ((this._fullname != value))
			{
				this.OnfullnameChanging(value);
				this.SendPropertyChanging();
				this._fullname = value;
				this.SendPropertyChanged("fullname");
				this.OnfullnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plec_id", DbType="Int")]
	public System.Nullable<int> plec_id
	{
		get
		{
			return this._plec_id;
		}
		set
		{
			if ((this._plec_id != value))
			{
				this.Onplec_idChanging(value);
				this.SendPropertyChanging();
				this._plec_id = value;
				this.SendPropertyChanged("plec_id");
				this.Onplec_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthdate", DbType="Date")]
	public System.Nullable<System.DateTime> birthdate
	{
		get
		{
			return this._birthdate;
		}
		set
		{
			if ((this._birthdate != value))
			{
				this.OnbirthdateChanging(value);
				this.SendPropertyChanging();
				this._birthdate = value;
				this.SendPropertyChanged("birthdate");
				this.OnbirthdateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opis", DbType="VarChar(500)")]
	public string opis
	{
		get
		{
			return this._opis;
		}
		set
		{
			if ((this._opis != value))
			{
				this.OnopisChanging(value);
				this.SendPropertyChanging();
				this._opis = value;
				this.SendPropertyChanged("opis");
				this.OnopisChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wojewodztwo_id", DbType="Int")]
	public System.Nullable<int> wojewodztwo_id
	{
		get
		{
			return this._wojewodztwo_id;
		}
		set
		{
			if ((this._wojewodztwo_id != value))
			{
				this.Onwojewodztwo_idChanging(value);
				this.SendPropertyChanging();
				this._wojewodztwo_id = value;
				this.SendPropertyChanged("wojewodztwo_id");
				this.Onwojewodztwo_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_user_profile", Storage="_aspnet_User", ThisKey="userid", OtherKey="UserId", IsForeignKey=true)]
	public aspnet_User aspnet_User
	{
		get
		{
			return this._aspnet_User.Entity;
		}
		set
		{
			aspnet_User previousValue = this._aspnet_User.Entity;
			if (((previousValue != value) 
						|| (this._aspnet_User.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._aspnet_User.Entity = null;
					previousValue.user_profile = null;
				}
				this._aspnet_User.Entity = value;
				if ((value != null))
				{
					value.user_profile = this;
					this._userid = value.UserId;
				}
				else
				{
					this._userid = default(System.Guid);
				}
				this.SendPropertyChanged("aspnet_User");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_sport")]
public partial class user_sport : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _userid;
	
	private int _sport_id;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuseridChanging(System.Guid value);
    partial void OnuseridChanged();
    partial void Onsport_idChanging(int value);
    partial void Onsport_idChanged();
    #endregion
	
	public user_sport()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this.OnuseridChanging(value);
				this.SendPropertyChanging();
				this._userid = value;
				this.SendPropertyChanged("userid");
				this.OnuseridChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sport_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int sport_id
	{
		get
		{
			return this._sport_id;
		}
		set
		{
			if ((this._sport_id != value))
			{
				this.Onsport_idChanging(value);
				this.SendPropertyChanging();
				this._sport_id = value;
				this.SendPropertyChanged("sport_id");
				this.Onsport_idChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class PokazOdwiedzoneResult
{
	
	private System.Guid _UserId;
	
	private string _username;
	
	private System.DateTime _Data;
	
	private string _Opis;
	
	private string _plec;
	
	private System.Nullable<int> _Wiek;
	
	private string _wojewodztwo;
	
	public PokazOdwiedzoneResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				this._UserId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this._username = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="DateTime NOT NULL")]
	public System.DateTime Data
	{
		get
		{
			return this._Data;
		}
		set
		{
			if ((this._Data != value))
			{
				this._Data = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", DbType="VarChar(500)")]
	public string Opis
	{
		get
		{
			return this._Opis;
		}
		set
		{
			if ((this._Opis != value))
			{
				this._Opis = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plec", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string plec
	{
		get
		{
			return this._plec;
		}
		set
		{
			if ((this._plec != value))
			{
				this._plec = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wiek", DbType="Int")]
	public System.Nullable<int> Wiek
	{
		get
		{
			return this._Wiek;
		}
		set
		{
			if ((this._Wiek != value))
			{
				this._Wiek = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wojewodztwo", DbType="NVarChar(50)")]
	public string wojewodztwo
	{
		get
		{
			return this._wojewodztwo;
		}
		set
		{
			if ((this._wojewodztwo != value))
			{
				this._wojewodztwo = value;
			}
		}
	}
}

public partial class SzukajResult
{
	
	private System.Guid _userid;
	
	private string _username;
	
	private string _fullname;
	
	private string _opis;
	
	private string _plec;
	
	private System.Nullable<System.DateTime> _birthdate;
	
	private System.Nullable<int> _wojewodztwo_id;
	
	public SzukajResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this._userid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this._username = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(50)")]
	public string fullname
	{
		get
		{
			return this._fullname;
		}
		set
		{
			if ((this._fullname != value))
			{
				this._fullname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opis", DbType="VarChar(500)")]
	public string opis
	{
		get
		{
			return this._opis;
		}
		set
		{
			if ((this._opis != value))
			{
				this._opis = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plec", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string plec
	{
		get
		{
			return this._plec;
		}
		set
		{
			if ((this._plec != value))
			{
				this._plec = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthdate", DbType="Date")]
	public System.Nullable<System.DateTime> birthdate
	{
		get
		{
			return this._birthdate;
		}
		set
		{
			if ((this._birthdate != value))
			{
				this._birthdate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wojewodztwo_id", DbType="Int")]
	public System.Nullable<int> wojewodztwo_id
	{
		get
		{
			return this._wojewodztwo_id;
		}
		set
		{
			if ((this._wojewodztwo_id != value))
			{
				this._wojewodztwo_id = value;
			}
		}
	}
}

public partial class CountWiekResult
{
	
	private System.Nullable<int> _c1;
	
	public CountWiekResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c1", DbType="Int")]
	public System.Nullable<int> c1
	{
		get
		{
			return this._c1;
		}
		set
		{
			if ((this._c1 != value))
			{
				this._c1 = value;
			}
		}
	}
}
#pragma warning restore 1591
